### ISSUE TITLE
Completar la pagina Not Found, que esta vacia.

### ISSUE THREAD

**Issue by DanielRicra** [DanielRicra/pf-videogames#21]
Alguien puede completar la pagina NotFound, con:
 - un mensaje en el centro que diga: Ops! this page doesn't exist. 
 - Un boton para regresar a la página principal.

**Comment by DanielRicra** [comment]
Al momento the hacer el commit de los cambios en NotFound agregar #21 al mesaje de commit: ejemplo `git commit -m "Update NotFound ... #21"`

**Comment by LiamOtegui** [comment]
Ahora lo hago 👍
